export default function () {
    return [
        { Code: "JS4006", Method: "Best 5", UQScore: 24, MedianScore: 23, LQScore: 23 , Course: "Anthropology" },
        { Code: "JS4018", Method: "Best 5", UQScore: 28, MedianScore: 27, LQScore: 26 , Course: "Chinese Language and Literature" },
        { Code: "JS4020", Method: "Best 5", UQScore: 24, MedianScore: 23, LQScore: 22 , Course: "Cultural Studies" },
        { Code: "JS4022", Method: "Best 5", UQScore: 24, MedianScore: 23, LQScore: 23 , Course: "Cultural Management" },
        { Code: "JS4032", Method: "4C2X", UQS1core: 27, MedianScore: 27, LQScore: 26 , Course: "English" },
        { Code: "JS4044", Method: "4C2X", UQScore: 31, MedianScore: 28, LQScore: 27 , Course: "Fine Arts" },
        { Code: "JS4056", Method: "Best 5", UQScore: 26, MedianScore: 25, LQScore: 24 , Course: "History" },
        { Code: "JS4068", Method: "Best 5", UQScore: 25, MedianScore: 24, LQScore: 24 , Course: "Japanese Studies" },
        { Code: "JS4070", Method: "Best 5", UQScore: 26, MedianScore: 24, LQScore: 24 , Course: "Linguistics" },
        { Code: "JS4082", Method: "Best 5", UQScore: 27, MedianScore: 24, LQScore: 22 , Course: "Music" },
        { Code: "JS4094", Method: "Best 5", UQScore: 24, MedianScore: 23, LQScore: 23 , Course: "Philosophy" },
        { Code: "JS4109", Method: "Best 5", UQScore: 22, MedianScore: 22, LQScore: 21 , Course: "Religious Studies" },
        { Code: "JS4123", Method: "Best 5", UQScore: 29, MedianScore: 28, LQScore: 27 , Course: "Translation" },
        { Code: "JS4202", Method: "Best 5", UQScore: 26, MedianScore: 25, LQScore: 24 , Course: "Integrated Bachelor of Business Administration Programme" },
        { Code: "JS4214", Method: "4C2X", UQScore: 41, MedianScore: 39, LQScore: 38 , Course: "Global Business Studies" },
        { Code: "JS4226", Method: "Best 5", UQScore: 25, MedianScore: 24, LQScore: 23 , Course: "Hospitality and Real Estate" },
        { Code: "JS4238", Method: "Best 5", UQScore: 30, MedianScore: 28, LQScore: 28 , Course: "Insurance, Financial and Actuarial Analysis" },
        { Code: "JS4240", Method: "Best 5", UQScore: 27, MedianScore: 26, LQScore: 25 , Course: "Professional Accountancy" },
        { Code: "JS4252", Method: "Best 5", UQScore: 31, MedianScore: 30, LQScore: 30 , Course: "Quantitative Finance " },
        { Code: "JS4254", Method: "4C2X", UQScore: 33, MedianScore: 32, LQScore: 32 , Course: "Interdisciplinary Major Programme in Global Economics and Finance" },
        { Code: "JS4276", Method: "Best 5", UQScore: 34, MedianScore: 32, LQScore: 31 , Course: "Quantitative Finance and Risk Management Science" },
        { Code: "JS4288", Method: "4C2X", UQScore: 36, MedianScore: 36, LQScore: 35 , Course: "International Business and Chinese Enterprise" },
        { Code: "JS4329", Method: "Best 5", UQScore: 26, MedianScore: 26, LQScore: 25 , Course: "Physical Education, Exercise Science and Health" },
        { Code: "JS4331", Method: "Best 5", UQScore: 27, MedianScore: 25, LQScore: 25 , Course: "B.A. (Chinese Language Studies) and B.Ed. (Chinese Language Education)" },
        { Code: "JS4343", Method: "Best 5", UQScore: 26, MedianScore: 24, LQScore: 23 , Course: "B.A. (English Studies) and B.Ed. (English Language Education)" },
        { Code: "JS4355", Method: "Best 5", UQScore: 23, MedianScore: 22, LQScore: 22 , Course: "Liberal Studies" },
        { Code: "JS4361", Method: "Best 5", UQScore: 27, MedianScore: 25, LQScore: 24 , Course: "B.Ed. in Mathematics and Mathematics Education" },
        { Code: "JS4401", Method: "Best 5", UQScore: 22, MedianScore: 21, LQScore: 20 , Course: "Engineering" },
        { Code: "JS4428", Method: "Best 5", UQScore: 27, MedianScore: 26, LQScore: 25 , Course: "BEng in Financial Technology" },
        { Code: "JS4434", Method: "Best 5", UQScore: 22, MedianScore: 21, LQScore: 20 , Course: "BEng in Electronic Engineering" },
        { Code: "JS4460", Method: "Best 5", UQScore: 28, MedianScore: 26, LQScore: 25 , Course: "BEng in Biomedical Engineering" },
        { Code: "JS4462", Method: "Best 5", UQScore: 23, MedianScore: 22, LQScore: 21 , Course: "BEng in Energy and Environmental Engineering" },
        { Code: "JS4903", Method: "4C2X", UQScore: 33, MedianScore: 32, LQScore: 32 , Course: "Bachelor of Laws" },
        { Code: "JS4264", Method: "4C2X", UQScore: 33, MedianScore: 33, LQScore: 33 , Course: "BBA (IBBA) - JD Double Degree Programme" },
        { Code: "JS4501", Method: "4C2X", UQScore: 37, MedianScore: 36, LQScore: 35 , Course: "Medicine (MBChB) Programme" },
        { Code: "JS4502", Method: "4C2X", UQScore: 41, MedianScore: 40, LQScore: 39 , Course: "Medicine (MBChB) Programme Global Physician-Leadership Stream (GPS)" },
        { Code: "JS4513", Method: "4C2X", UQScore: 31, MedianScore: 29, LQScore: 29 , Course: "Nursing" },
        { Code: "JS4525", Method: "4C2X", UQScore: 34, MedianScore: 33, LQScore: 32 , Course: "Pharmacy" },
        { Code: "JS4537", Method: "Best 5", UQScore: 27, MedianScore: 25, LQScore: 24 , Course: "Public Health" },
        { Code: "JS4542", Method: "4C2X", UQScore: 34, MedianScore: 32, LQScore: 32 , Course: "Chinese Medicine" },
        { Code: "JS4550", Method: "4C2X", UQScore: 35, MedianScore: 34, LQScore: 33 , Course: "Biomedical Sciences" },
        { Code: "JS4601", Method: "Best 5", UQScore: 24, MedianScore: 23, LQScore: 22 , Course: "Science" },
        { Code: "JS4633", Method: "Best 5", UQScore: 27, MedianScore: 27, LQScore: 26 , Course: "Earth System Science (Atmospheric Science / Geophysics)" },
        { Code: "JS4682", Method: "Best 5", UQScore: 32, MedianScore: 30, LQScore: 29 , Course: "Enrichment Mathematics" },
        { Code: "JS4690", Method: "Best 5", UQScore: 32, MedianScore: 31, LQScore: 29 , Course: "Enrichment Stream in Theoretical Physics" },
        { Code: "JS4719", Method: "Best 5", UQScore: 28, MedianScore: 27, LQScore: 26 , Course: "Risk Management Science" },
        { Code: "JS4801", Method: "Best 5", UQScore: 27, MedianScore: 26, LQScore: 25 , Course: "Social Science" },
        { Code: "JS4812", Method: "Best 5", UQScore: 30, MedianScore: 28, LQScore: 27 , Course: "Architectural Studies" },
        { Code: "JS4824", Method: "Best 5", UQScore: 25, MedianScore: 24, LQScore: 23 , Course: "Economics" },
        { Code: "JS4836", Method: "Best 5", UQScore: 26, MedianScore: 25, LQScore: 24 , Course: "Geography and Resource Management" },
        { Code: "JS4838", Method: "Best 5", UQScore: 27, MedianScore: 26, LQScore: 24 , Course: "Urban Studies" },
        { Code: "JS4848", Method: "4C2X", UQScore: 31, MedianScore: 29, LQScore: 28 , Course: "Government and Public Administration" },
        { Code: "JS4850", Method: "Best 5", UQScore: 29, MedianScore: 28, LQScore: 27 , Course: "Journalism and Communication" },
        { Code: "JS4858", Method: "Best 5", UQScore: 30, MedianScore: 28, LQScore: 27 , Course: "Global Communication" },
        { Code: "JS4862", Method: "Best 5", UQScore: 29, MedianScore: 27, LQScore: 27 , Course: "Psychology" },
        { Code: "JS4874", Method: "Best 5", UQScore: 28, MedianScore: 26, LQScore: 25 , Course: "Social Work" },
        { Code: "JS4886", Method: "Best 5", UQScore: 24, MedianScore: 24, LQScore: 23 , Course: "Sociology" },
        { Code: "JS4892", Method: "Best 5", UQScore: 27, MedianScore: 26, LQScore: 26 , Course: "Global Studies" },
       
    ]
}
