//database, which should be using SQL database instead (improvement required)
//improvement on database will be done asap
export default function () {
    return [
        { Code: "JS6004", Method: "Best 5", MedianScore: 25, LQScore: 24, Course: "BA(AS)", MinLevelRequired: "Testing-function" },
        { Code: "JS6016", Method: "Best 5", MedianScore: 25, LQScore: 24, Course: "BSC(SURV)", MinLevelRequired: "Testing-function" },
        { Code: "JS6028", Method: "Best 5", MedianScore: 25, LQScore: 24, Course: "BA(LS)", MinLevelRequired: "Testing-function" },
        { Code: "JS6030", Method: "Best 5", MedianScore: 25, LQScore: 24, Course: "BA(Conservation)", MinLevelRequired: "Testing-function" },
        { Code: "JS6042", Method: "Best 5", MedianScore: 25, LQScore: 24, Course: "BA(US)", MinLevelRequired: "Testing-function" },
        { Code: "JS6054", Method: "Best 5", MedianScore: 25, LQScore: 24, Course: "BA", MinLevelRequired: "Testing-function" },
        { Code: "JS6767", Method: "4C2X", MedianScore: 25, LQScore: 24, Course: "BEcon/BEcon&Fin", MinLevelRequired: "Testing-function" },
        { Code: "JS6781", Method: "4C2X", MedianScore: 25, LQScore: 24, Course: "BBA/BBA(Acc&Fin)", MinLevelRequired: "Testing-function" },
        { Code: "JS6793", Method: "4C2X", MedianScore: 25, LQScore: 24, Course: "BBA(IS)", MinLevelRequired: "Testing-function" },
        { Code: "JS6808", Method: "4C2X", MedianScore: 25, LQScore: 24, Course: "BBA(Law)&LLB", MinLevelRequired: "Testing-function" },
        { Code: "JS6884", Method: "4C2X", MedianScore: 25, LQScore: 24, Course: "BSc(QFin)", MinLevelRequired: "Testing-function" },
        { Code: "JS6896", Method: "4C2X", MedianScore: 25, LQScore: 24, Course: "BBA(IBGM)", MinLevelRequired: "Testing-function" },
        { Code: "JS6107", Method: "4C2X", MedianScore: 25, LQScore: 24, Course: "BDS", MinLevelRequired: "Testing-function" },
        { Code: "JS6066", Method: "Best 5", MedianScore: 25, LQScore: 24, Course: "BA&BED(LangEd)-Eng", MinLevelRequired: "Testing-function" },
        { Code: "JS6080", Method: "Best 5", MedianScore: 25, LQScore: 24, Course: "BA&BED(LangEd)-Chin", MinLevelRequired: "Testing-function" },
        { Code: "JS6119", Method: "Best 5", MedianScore: 25, LQScore: 24, Course: "BED&BSC", MinLevelRequired: "Testing-function" },
        { Code: "JS6157", Method: "4C2X", MedianScore: 25, LQScore: 24, Course: "BSC(SPEECH)", MinLevelRequired: "Testing-function" },
        { Code: "JS6195", Method: "Best 5", MedianScore: 28, LQScore: 24, Course: "BED&BSS", MinLevelRequired: "Testing-function" },
        { Code: "JS6951", Method: "Best 5", MedianScore: 28, LQScore: 24, Course: "BENG(EngSc)", MinLevelRequired: "Testing-function" },
        { Code: "JS6763", Method: "Best 5", MedianScore: 28, LQScore: 24, Course: "BENG", MinLevelRequired: "Testing-function" },
        { Code: "JS6078", Method: "4C2X", MedianScore: 28, LQScore: 30, Course: "BA(Literary Studies)&LLB ", MinLevelRequired: "Testing-function" },
        { Code: "JS6406", Method: "4C2X", MedianScore: 28, LQScore: 30, Course: "LLB", MinLevelRequired: "Testing-function" },
        { Code: "JS6183", Method: "", MedianScore: 28, LQScore: 30, Course: "BSC(Exercise&Health)", MinLevelRequired: "Testing-function" },
        { Code: "JS6456", Method: "Best 6", MedianScore: 28, LQScore: 30, Course: "MBBS", MinLevelRequired: "Testing-function" },
        { Code: "JS6468", Method: "Best 5", MedianScore: 28, LQScore: 30, Course: "BNURS", MinLevelRequired: "Testing-function" },
        { Code: "JS6482", Method: "Best 5", MedianScore: 28, LQScore: 30, Course: "BChinMed", MinLevelRequired: "Testing-function" },
        { Code: "JS6494", Method: "Best 6", MedianScore: 28, LQScore: 30, Course: "BPharm", MinLevelRequired: "Testing-function" },
        { Code: "JS6949", Method: "Best 6", MedianScore: 28, LQScore: 30, Course: "BBiomedSc", MinLevelRequired: "Testing-function" },
        { Code: "JS6729", Method: "Best 6", MedianScore: 32, LQScore: 30, Course: "BSC(AC)", MinLevelRequired: "Testing-function" },
        { Code: "JS6901", Method: "Best 5", MedianScore: 32, LQScore: 30, Course: "BSC", MinLevelRequired: "Testing-function" },
        { Code: "JS6717", Method: "Best 5", MedianScore: 32, LQScore: 30, Course: "BSS", MinLevelRequired: "Testing-function" },
        { Code: "JS6731", Method: "Best 5", MedianScore: 32, LQScore: 30, Course: "BSW", MinLevelRequired: "Testing-function" },
        { Code: "JS6810", Method: "4C2X", MedianScore: 32, LQScore: 30, Course: "BSS(GL)&LLB", MinLevelRequired: "Testing-function" },
        { Code: "JS6822", Method: "Best 5", MedianScore: 32, LQScore: 30, Course: "BJ", MinLevelRequired: "Testing-function" }
    ];
}